### ISSUE TITLE
z这是怎么回事啊？

### ISSUE THREAD

**Issue by juzhijian** [Vlvxingze/VLagger#17]
[19:58:49 WARN]: java.lang.reflect.InvocationTargetException
[19:58:49 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:58:49 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:58:49 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:58:49 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:58:49 WARN]:        at com.intellectualcrafters.plot.util.block.QueueProvider$1.getNewQueue(QueueProvider.java:15)
[19:58:49 WARN]:        at com.intellectualcrafters.plot.util.block.GlobalBlockQueue.getNewQueue(GlobalBlockQueue.java:69)
[19:58:49 WARN]:        at com.plotsquared.bukkit.generator.BukkitPlotGenerator$1.populate(BukkitPlotGenerator.java:59)
[19:58:49 WARN]:        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:460)
[19:58:49 WARN]:        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1201)
[19:58:49 WARN]:        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
[19:58:49 WARN]:        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
[19:58:49 WARN]:        at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408)
[19:58:49 WARN]:        at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121)
[19:58:49 WARN]:        at net.minecraft.server.management.PlayerManager.func_72683_a(PlayerManager.java:176)
[19:58:49 WARN]:        at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(ServerConfigurationManager.java:304)
[19:58:49 WARN]:        at thermos.thermite.ThermiteTeleportationHandler.transferPlayerToDimension(ThermiteTeleportationHandler.java:92)
[19:58:49 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:514)
[19:58:49 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:410)
[19:58:49 WARN]:        at com.mcml.space.optimize.TeleportPreLoader$10.run(TeleportPreLoader.java:141)
[19:58:49 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[19:58:49 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[19:58:49 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[19:58:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[19:58:49 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[19:58:49 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[19:58:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:58:49 WARN]: Caused by: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Block
[19:58:49 WARN]:        at java.lang.Class.forName0(Native Method)
[19:58:49 WARN]:        at java.lang.Class.forName(Class.java:264)
[19:58:49 WARN]:        at com.intellectualcrafters.plot.util.ReflectionUtils.getRefClass(ReflectionUtils.java:215)
[19:58:49 WARN]:        at com.plotsquared.bukkit.util.block.BukkitLocalQueue_1_7.<init>(BukkitLocalQueue_1_7.java:24)
[19:58:49 WARN]:        ... 26 more

**Comment by Vlvxingze** [comment]
额，抱歉现在才回复，总之修复了
