### ISSUE TITLE
我用多世界加载了一个世界之后就开始报错了。

### ISSUE THREAD

**Issue by juzhijian** [Vlvxingze/VLagger#2]
[16:17:46 WARN]: [VLagger] Task #33 for VLagger v2.0.0 generated an exception
java.lang.AssertionError: 5
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftSkull.getSkullType(CraftSkull.java:43) ~[CraftSkull.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftSkull.<init>(CraftSkull.java:26) ~[CraftSkull.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.getState(CraftBlock.java:300) ~[CraftBlock.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftChunk.getTileEntities(CraftChunk.java:114) ~[CraftChunk.class:1.7.10-1614.57]
        at com.mcml.space.optimize.TilesClear.run(TilesClear.java:24) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.57]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Vlvxingze** [comment]
收到，你所反馈的问题将于3天之内修复。
预计修复时间（8小时）
感谢！

**Comment by SotrForgotten** [comment]
使用最新构建（见circleci），或关闭TilesClear功能即可解决。

**Comment by Vlvxingze** [comment]
重新打开：
问题已经找到：
在1.8以下（包括1.7.10）
是没有 tile.update方法的，尽管我已经catch，但仍然可能导致服务端出现崩溃。
解决方法：用VersionLevel判断版本，如果超过1.8则允许使用，否则return

**Comment by SotrForgotten** [comment]
@Vlvxingze 但是，tile.update()方法本身就比较耗时 我建议还是直接移除这个功能

**Comment by Vlvxingze** [comment]
额？耗时吗。。
我自己测试过= =
不耗时的，执行5000次也不超过50MS

**Comment by SotrForgotten** [comment]
@Vlvxingze 而且，这个crash并不是找不到方法导致的

**Comment by Vlvxingze** [comment]
已删除
