### ISSUE TITLE
Lib issue

### ISSUE THREAD

**Issue by juzhijian** [Vlvxingze/VLagger#7]
[22:26:13 ERROR]: Error occurred while enabling VLagger v2.8.2-171 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
        at com.mcml.space.optimize.TeleportPreloader.<clinit>(TeleportPreloader.java:30) ~[?:?]
        at com.mcml.space.core.VLagger.onEnable(VLagger.java:146) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

**Comment by juzhijian** [comment]
[22:27:53 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to VLagger v2.8.2-171
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489) [SimplePluginManager.class:1.7.10-1614.57]
        at net.minecraft.server.network.ThreadPlayerLookupUUID.fireLoginEvents(ThreadPlayerLookupUUID.java:99) [ThreadPlayerLookupUUID.class:?]
        at net.minecraft.server.network.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:40) [ThreadPlayerLookupUUID.class:?]
Caused by: java.lang.NullPointerException
        at com.mcml.space.fix.FixDupeLogin.CheckDoubleOnline(FixDupeLogin.java:22) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 5 more

**Comment by Vlvxingze** [comment]
收到，你的问题将于3天之内修复

**Comment by juzhijian** [comment]
这个BUG现在有什么影响？

**Comment by Vlvxingze** [comment]
临时解决中，预计今日下午9点解决（临时注释代码）

**Comment by SotrForgotten** [comment]
请尝试最新构建，无法使用请反馈

**Comment by SotrForgotten** [comment]
已经通过低版本不启用缓存的方式解决
