### ISSUE TITLE
任务：修复TeleportPreLoader代码

### ISSUE THREAD

**Issue by Vlvxingze** [Vlvxingze/VLagger#8]
在开服时：TeleportPreLoader中出现报错：
public static final Cache<Location, List<Coord2D>> caches = CacheBuilder.newBuilder().maximumSize(Bukkit.getMaxPlayers() > 256 ? 256 : (Bukkit.getMaxPlayers() < 64 ? 64 : Bukkit.getMaxPlayers())).expireAfterWrite(5, TimeUnit.MINUTES).build();
这部分报错：
原因：
[19:43:42] [Server thread/ERROR]: Error occurred while enabling VLagger v2.8.3-185 (Is it up to date?)
	java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.maximumSize(J)Lguava10/com/google/common/cache/CacheBuilder;
at com.mcml.space.optimize.TeleportPreloader.<clinit>(TeleportPreloader.java:32) ~[?:?]
at com.mcml.space.core.VLagger.onEnable(VLagger.java:152) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1199.01.149]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:360) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1199.01.149]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1199.01.149]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:413) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1199.01.149]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:347) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1199.01.149]
at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:504) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:478) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:438) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by SotrForgotten** [comment]
fixed
